title: "LOST"
theme: just-the-docs
color_scheme: "nil"
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
# Supports true (default) or false/nil
heading_anchors: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jemoji
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-relative-links
  - jekyll-titles-from-headings

# Adding for mathjax support
compress_html:
  blanklines: true

mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'

markdown: kramdown

kramdown:
  input: GFM
  hand_wrap: false
  syntax_highligher: rouge
  syntax_highligher_opts:
    default_lang: plaintext

highlighter: rouge

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/lost-stats/lost-stats.github.io"
gh_edit_branch: "source" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately